name: Build portal
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci-build]')
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin
      - name: Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o portal_linux_amd64 -ldflags="-s -w" -v .
      - name: Linux ARM
        run: GOOS=linux GOARCH=arm go build -o portal_linux_arm -ldflags="-s -w" -v .
      - name: Windows AMD64
        run: GOOS=windows GOARCH=amd64 go build -o portal_windows_amd64.exe -ldflags="-s -w" -v .
      - name: Windows ARM
        run: GOOS=windows GOARCH=arm go build -o portal_windows_arm.exe -ldflags="-s -w" -v .
      - name: Darwin AMD64
        run: GOOS=darwin GOARCH=amd64 go build -o portal_darwin_amd64 -ldflags="-s -w" -v .
      - name: Upload Artifacts
        env:
          HOST: ${{ secrets.HOST }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa $HOST mkdir $GITHUB_SHA
          scp -i ~/.ssh/id_rsa portal_linux_amd64 $HOST:/home/paroxity/%GITHUB_SHA/portal_linux_amd64
          scp -i ~/.ssh/id_rsa portal_linux_arm $HOST:/home/paroxity/%GITHUB_SHA/portal_linux_arm
          scp -i ~/.ssh/id_rsa portal_windows_amd64.exe $HOST:/home/paroxity/%GITHUB_SHA/portal_windows_amd64.exe
          scp -i ~/.ssh/id_rsa portal_windows_arm.exe $HOST:/home/paroxity/%GITHUB_SHA/portal_windows_arm.exe
          scp -i ~/.ssh/id_rsa portal_darwin_amd64 $HOST:/home/paroxity/%GITHUB_SHA/portal_darwin_amd64